language: php
php:
 - '5.5'
 - '5.6'
 - '7.0'
 - '7.1'
 - hhvm # on Trusty only
 - nightly

# Commands to be run before your environment runs.
before_script:
  - composer self-update
  - composer install --no-interaction

# Commands you want to run that will verify your build.
script: ./phpunit
